package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ActiveEmployeeContactInformationMapper {

	int countByCompanyEmailAsPassword(String checkEmail);

	int selectActiveEmployeeContactInformationIdByEmail(String companyEmail);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(ActiveEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(ActiveEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer activeEmployeeContactInformationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(ActiveEmployeeContactInformation row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(ActiveEmployeeContactInformation row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<ActiveEmployeeContactInformation> selectByExample(ActiveEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	ActiveEmployeeContactInformation selectByPrimaryKey(Integer activeEmployeeContactInformationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") ActiveEmployeeContactInformation row,
			@Param("example") ActiveEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") ActiveEmployeeContactInformation row,
			@Param("example") ActiveEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(ActiveEmployeeContactInformation row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.active_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(ActiveEmployeeContactInformation row);
}