package com.employee.managementapi.infrastructure.employee;

import java.util.Date;

public class AssignedTeam {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.assigned_team.assigned_team_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer assignedTeamId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.assigned_team.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.assigned_team.team_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer teamId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.assigned_team.assigned_team_date
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Date assignedTeamDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.assigned_team.assigned_team_id
	 * @return  the value of employee.assigned_team.assigned_team_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getAssignedTeamId() {
		return assignedTeamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.assigned_team.assigned_team_id
	 * @param assignedTeamId  the value for employee.assigned_team.assigned_team_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setAssignedTeamId(Integer assignedTeamId) {
		this.assignedTeamId = assignedTeamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.assigned_team.employee_id
	 * @return  the value of employee.assigned_team.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.assigned_team.employee_id
	 * @param employeeId  the value for employee.assigned_team.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.assigned_team.team_id
	 * @return  the value of employee.assigned_team.team_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getTeamId() {
		return teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.assigned_team.team_id
	 * @param teamId  the value for employee.assigned_team.team_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.assigned_team.assigned_team_date
	 * @return  the value of employee.assigned_team.assigned_team_date
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Date getAssignedTeamDate() {
		return assignedTeamDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.assigned_team.assigned_team_date
	 * @param assignedTeamDate  the value for employee.assigned_team.assigned_team_date
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setAssignedTeamDate(Date assignedTeamDate) {
		this.assignedTeamDate = assignedTeamDate;
	}
}