package com.employee.managementapi.infrastructure.employee;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AssignedTeamExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public AssignedTeamExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andAssignedTeamIdIsNull() {
			addCriterion("assigned_team_id is null");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdIsNotNull() {
			addCriterion("assigned_team_id is not null");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdEqualTo(Integer value) {
			addCriterion("assigned_team_id =", value, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdNotEqualTo(Integer value) {
			addCriterion("assigned_team_id <>", value, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdGreaterThan(Integer value) {
			addCriterion("assigned_team_id >", value, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("assigned_team_id >=", value, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdLessThan(Integer value) {
			addCriterion("assigned_team_id <", value, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdLessThanOrEqualTo(Integer value) {
			addCriterion("assigned_team_id <=", value, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdIn(List<Integer> values) {
			addCriterion("assigned_team_id in", values, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdNotIn(List<Integer> values) {
			addCriterion("assigned_team_id not in", values, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdBetween(Integer value1, Integer value2) {
			addCriterion("assigned_team_id between", value1, value2, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamIdNotBetween(Integer value1, Integer value2) {
			addCriterion("assigned_team_id not between", value1, value2, "assignedTeamId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNull() {
			addCriterion("employee_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNotNull() {
			addCriterion("employee_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdEqualTo(Integer value) {
			addCriterion("employee_id =", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotEqualTo(Integer value) {
			addCriterion("employee_id <>", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThan(Integer value) {
			addCriterion("employee_id >", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employee_id >=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThan(Integer value) {
			addCriterion("employee_id <", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThanOrEqualTo(Integer value) {
			addCriterion("employee_id <=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIn(List<Integer> values) {
			addCriterion("employee_id in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotIn(List<Integer> values) {
			addCriterion("employee_id not in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdBetween(Integer value1, Integer value2) {
			addCriterion("employee_id between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employee_id not between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andTeamIdIsNull() {
			addCriterion("team_id is null");
			return (Criteria) this;
		}

		public Criteria andTeamIdIsNotNull() {
			addCriterion("team_id is not null");
			return (Criteria) this;
		}

		public Criteria andTeamIdEqualTo(Integer value) {
			addCriterion("team_id =", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotEqualTo(Integer value) {
			addCriterion("team_id <>", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdGreaterThan(Integer value) {
			addCriterion("team_id >", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("team_id >=", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdLessThan(Integer value) {
			addCriterion("team_id <", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdLessThanOrEqualTo(Integer value) {
			addCriterion("team_id <=", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdIn(List<Integer> values) {
			addCriterion("team_id in", values, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotIn(List<Integer> values) {
			addCriterion("team_id not in", values, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdBetween(Integer value1, Integer value2) {
			addCriterion("team_id between", value1, value2, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotBetween(Integer value1, Integer value2) {
			addCriterion("team_id not between", value1, value2, "teamId");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateIsNull() {
			addCriterion("assigned_team_date is null");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateIsNotNull() {
			addCriterion("assigned_team_date is not null");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateEqualTo(Date value) {
			addCriterionForJDBCDate("assigned_team_date =", value, "assignedTeamDate");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("assigned_team_date <>", value, "assignedTeamDate");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateGreaterThan(Date value) {
			addCriterionForJDBCDate("assigned_team_date >", value, "assignedTeamDate");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("assigned_team_date >=", value, "assignedTeamDate");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateLessThan(Date value) {
			addCriterionForJDBCDate("assigned_team_date <", value, "assignedTeamDate");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("assigned_team_date <=", value, "assignedTeamDate");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateIn(List<Date> values) {
			addCriterionForJDBCDate("assigned_team_date in", values, "assignedTeamDate");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("assigned_team_date not in", values, "assignedTeamDate");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("assigned_team_date between", value1, value2, "assignedTeamDate");
			return (Criteria) this;
		}

		public Criteria andAssignedTeamDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("assigned_team_date not between", value1, value2, "assignedTeamDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.assigned_team
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee.assigned_team
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 23 17:01:09 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}