package com.employee.managementapi.infrastructure.employee;

import java.util.Date;

public class AssignedDivision {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.assigned_division.assigned_division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer assignedDivisionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.assigned_division.division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer divisionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.assigned_division.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.assigned_division.assigned_division_date
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Date assignedDivisionDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.assigned_division.assigned_division_id
	 * @return  the value of employee.assigned_division.assigned_division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getAssignedDivisionId() {
		return assignedDivisionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.assigned_division.assigned_division_id
	 * @param assignedDivisionId  the value for employee.assigned_division.assigned_division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setAssignedDivisionId(Integer assignedDivisionId) {
		this.assignedDivisionId = assignedDivisionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.assigned_division.division_id
	 * @return  the value of employee.assigned_division.division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getDivisionId() {
		return divisionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.assigned_division.division_id
	 * @param divisionId  the value for employee.assigned_division.division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDivisionId(Integer divisionId) {
		this.divisionId = divisionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.assigned_division.employee_id
	 * @return  the value of employee.assigned_division.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.assigned_division.employee_id
	 * @param employeeId  the value for employee.assigned_division.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.assigned_division.assigned_division_date
	 * @return  the value of employee.assigned_division.assigned_division_date
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Date getAssignedDivisionDate() {
		return assignedDivisionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.assigned_division.assigned_division_date
	 * @param assignedDivisionDate  the value for employee.assigned_division.assigned_division_date
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setAssignedDivisionDate(Date assignedDivisionDate) {
		this.assignedDivisionDate = assignedDivisionDate;
	}
}