package com.employee.managementapi.infrastructure.employee;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssignmentProjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(AssignmentProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(AssignmentProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer assignmentProjectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(AssignmentProject row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(AssignmentProject row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<AssignmentProject> selectByExample(AssignmentProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	AssignmentProject selectByPrimaryKey(Integer assignmentProjectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") AssignmentProject row,
			@Param("example") AssignmentProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") AssignmentProject row, @Param("example") AssignmentProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(AssignmentProject row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.assignment_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(AssignmentProject row);
}