package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BelongingCompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(BelongingCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(BelongingCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer belongingCompanyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(BelongingCompany row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(BelongingCompany row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<BelongingCompany> selectByExample(BelongingCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	BelongingCompany selectByPrimaryKey(Integer belongingCompanyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") BelongingCompany row, @Param("example") BelongingCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") BelongingCompany row, @Param("example") BelongingCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(BelongingCompany row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(BelongingCompany row);

	int selectNextval();
}