package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BelongingDepartmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(BelongingDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(BelongingDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer belongingDepartmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(BelongingDepartment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(BelongingDepartment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<BelongingDepartment> selectByExample(BelongingDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	BelongingDepartment selectByPrimaryKey(Integer belongingDepartmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") BelongingDepartment row,
			@Param("example") BelongingDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") BelongingDepartment row, @Param("example") BelongingDepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(BelongingDepartment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_department
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(BelongingDepartment row);
}