package com.employee.managementapi.infrastructure.employee;

public class BelongingDivision {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.belonging_division.belonging_division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer belongingDivisionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.belonging_division.division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer divisionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.belonging_division.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.belonging_division.belonging_division_id
	 * @return  the value of employee.belonging_division.belonging_division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getBelongingDivisionId() {
		return belongingDivisionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.belonging_division.belonging_division_id
	 * @param belongingDivisionId  the value for employee.belonging_division.belonging_division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setBelongingDivisionId(Integer belongingDivisionId) {
		this.belongingDivisionId = belongingDivisionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.belonging_division.division_id
	 * @return  the value of employee.belonging_division.division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getDivisionId() {
		return divisionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.belonging_division.division_id
	 * @param divisionId  the value for employee.belonging_division.division_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDivisionId(Integer divisionId) {
		this.divisionId = divisionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.belonging_division.employee_id
	 * @return  the value of employee.belonging_division.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.belonging_division.employee_id
	 * @param employeeId  the value for employee.belonging_division.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}
}