package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BelongingProjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(BelongingProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(BelongingProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer belongingProjectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(BelongingProject row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(BelongingProject row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<BelongingProject> selectByExample(BelongingProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	BelongingProject selectByPrimaryKey(Integer belongingProjectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") BelongingProject row, @Param("example") BelongingProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") BelongingProject row, @Param("example") BelongingProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(BelongingProject row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.belonging_project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(BelongingProject row);
}