package com.employee.managementapi.infrastructure.employee;

import com.employee.managementapi.employee.company.belonging.EmployeeBelongingCompany;

import lombok.AllArgsConstructor;
import lombok.Builder;

@Builder
@AllArgsConstructor
public class BelongingCompany {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.belonging_company.belonging_company_id
     * 
     * @mbg.generated Mon Dec 26 23:16:33 JST 2022
     */
    private Integer belongingCompanyId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.belonging_company.company_id
     * 
     * @mbg.generated Mon Dec 26 23:16:33 JST 2022
     */
    private Integer companyId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column employee.belonging_company.employee_id
     * 
     * @mbg.generated Mon Dec 26 23:16:33 JST 2022
     */
    private Integer employeeId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.belonging_company.belonging_company_id
     * 
     * @return the value of employee.belonging_company.belonging_company_id
     * @mbg.generated Mon Dec 26 23:16:33 JST 2022
     */
    public Integer getBelongingCompanyId() {
        return belongingCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.belonging_company.belonging_company_id
     * 
     * @param belongingCompanyId the value for
     *                           employee.belonging_company.belonging_company_id
     * @mbg.generated Mon Dec 26 23:16:33 JST 2022
     */
    public void setBelongingCompanyId(Integer belongingCompanyId) {
        this.belongingCompanyId = belongingCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.belonging_company.company_id
     * 
     * @return the value of employee.belonging_company.company_id
     * @mbg.generated Mon Dec 26 23:16:33 JST 2022
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.belonging_company.company_id
     * 
     * @param companyId the value for employee.belonging_company.company_id
     * @mbg.generated Mon Dec 26 23:16:33 JST 2022
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column employee.belonging_company.employee_id
     * 
     * @return the value of employee.belonging_company.employee_id
     * @mbg.generated Mon Dec 26 23:16:33 JST 2022
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column employee.belonging_company.employee_id
     * 
     * @param employeeId the value for employee.belonging_company.employee_id
     * @mbg.generated Mon Dec 26 23:16:33 JST 2022
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * ドメインオブジェクトからインスタンスを生成
     * 
     * @param employeeBelongingCompany ドメインオブジェクト
     * @return DBエンティティのインスタンス
     */
    public static BelongingCompany build(final EmployeeBelongingCompany employeeBelongingCompany) {
        return BelongingCompany.builder()
                .companyId(employeeBelongingCompany.getCompanyId())
                .employeeId(employeeBelongingCompany.getEmployeeId())
                .build();
    }

    /**
     * DBエンティティをドメインオブジェクトへ変換
     * 
     * @return ドメインオブジェクト
     */
    public EmployeeBelongingCompany toDomainBelongCompany() {
        return EmployeeBelongingCompany.builder()
                .companyId(this.companyId)
                .employeeId(this.employeeId)
                .build();
    }
}