package com.employee.managementapi.infrastructure.employee;

public class BusinessPartner {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.business_partner.business_partner_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer businessPartnerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.business_partner.business_partner_code
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private String businessPartnerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.business_partner.business_partner_name
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private String businessPartnerName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.business_partner.business_partner_id
	 * @return  the value of employee.business_partner.business_partner_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getBusinessPartnerId() {
		return businessPartnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.business_partner.business_partner_id
	 * @param businessPartnerId  the value for employee.business_partner.business_partner_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setBusinessPartnerId(Integer businessPartnerId) {
		this.businessPartnerId = businessPartnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.business_partner.business_partner_code
	 * @return  the value of employee.business_partner.business_partner_code
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getBusinessPartnerCode() {
		return businessPartnerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.business_partner.business_partner_code
	 * @param businessPartnerCode  the value for employee.business_partner.business_partner_code
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setBusinessPartnerCode(String businessPartnerCode) {
		this.businessPartnerCode = businessPartnerCode == null ? null : businessPartnerCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.business_partner.business_partner_name
	 * @return  the value of employee.business_partner.business_partner_name
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getBusinessPartnerName() {
		return businessPartnerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.business_partner.business_partner_name
	 * @param businessPartnerName  the value for employee.business_partner.business_partner_name
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setBusinessPartnerName(String businessPartnerName) {
		this.businessPartnerName = businessPartnerName == null ? null : businessPartnerName.trim();
	}
}