package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CompanyAssignmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(CompanyAssignmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(CompanyAssignmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer companyAssignmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(CompanyAssignment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(CompanyAssignment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<CompanyAssignment> selectByExample(CompanyAssignmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	CompanyAssignment selectByPrimaryKey(Integer companyAssignmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") CompanyAssignment row,
			@Param("example") CompanyAssignmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") CompanyAssignment row, @Param("example") CompanyAssignmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(CompanyAssignment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company_assignment
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(CompanyAssignment row);

	int selectNextval();
}