package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer companyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(Company row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(Company row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<Company> selectByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	Company selectByPrimaryKey(Integer companyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") Company row, @Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") Company row, @Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(Company row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(Company row);

	int selectNextval();
}