package com.employee.managementapi.infrastructure.employee;

import com.employee.managementapi.company.CompanyWithPrimaryKey;

import lombok.AllArgsConstructor;
import lombok.Builder;

@Builder
@AllArgsConstructor
public class Company {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.company.company_id
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.company.company_code
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	private String companyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.company.company_name
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.company.company_business_content
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	private String companyBusinessContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.company.company_id
	 * 
	 * @return the value of employee.company.company_id
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.company.company_id
	 * 
	 * @param companyId the value for employee.company.company_id
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.company.company_code
	 * 
	 * @return the value of employee.company.company_code
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.company.company_code
	 * 
	 * @param companyCode the value for employee.company.company_code
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode == null ? null : companyCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.company.company_name
	 * 
	 * @return the value of employee.company.company_name
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.company.company_name
	 * 
	 * @param companyName the value for employee.company.company_name
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName == null ? null : companyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.company.company_business_content
	 * 
	 * @return the value of employee.company.company_business_content
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public String getCompanyBusinessContent() {
		return companyBusinessContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.company.company_business_content
	 * 
	 * @param companyBusinessContent the value for
	 *                               employee.company.company_business_content
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public void setCompanyBusinessContent(String companyBusinessContent) {
		this.companyBusinessContent = companyBusinessContent == null ? null : companyBusinessContent.trim();
	}

	/**
	 * ドメインオブジェクトからインスタンスを生成
	 * 
	 * @param company ドメインオブジェクト
	 * @return インスタンス
	 */
	public static Company build(final com.employee.managementapi.company.Company company) {
		return Company.builder()
				.companyCode(company.getCompanyCode())
				.companyName(company.getCompanyName())
				.companyBusinessContent(company.getCompanyBusinessContent())
				.build();
	}

	/**
	 * ドメインオブジェクトへ変換
	 * 
	 * @return ドメインオブジェクト
	 */
	public com.employee.managementapi.company.Company toDomainCompany() {
		return com.employee.managementapi.company.Company.builder()
				.companyCode(this.getCompanyCode())
				.companyName(this.getCompanyName())
				.companyBusinessContent(this.getCompanyBusinessContent())
				.build();
	}

	/**
	 * ドメインオブジェクトからインスタンスを生成
	 * 1/11 現在使用するユースケースは存在しないがサンプルとして記述する
	 * 
	 * @param companyWithPrimaryKey
	 * @return インスタンス
	 */
	public static Company build(final CompanyWithPrimaryKey companyWithPrimaryKey) {
		return Company.builder()
				.companyId(companyWithPrimaryKey.getCompanyId())
				.companyCode(companyWithPrimaryKey.getCompanyCode())
				.companyName(companyWithPrimaryKey.getCompanyName())
				.companyBusinessContent(companyWithPrimaryKey.getCompanyBusinessContent())
				.build();
	}

	/**
	 * ドメインオブジェクト主キー付きへ変換
	 * 1/11 現在使用するユースケースは存在しないがサンプルとして記述する
	 * 
	 * @return ドメインオブジェクト主キー付き
	 */
	public CompanyWithPrimaryKey toCompanyWithPrimaryKey() {
		return CompanyWithPrimaryKey.builder()
				.companyId(this.getCompanyId())
				.companyCode(this.getCompanyCode())
				.companyName(this.getCompanyName())
				.companyBusinessContent(this.getCompanyBusinessContent())
				.build();
	}

}