package com.employee.managementapi.infrastructure.employee;

public class ContactInformationForStaffOnLeave {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.contact_information_for_staff_on_leave.contact_information_for_staff_on_leave_id
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	private Integer contactInformationForStaffOnLeaveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.contact_information_for_staff_on_leave.employee_contact_information_id
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	private Integer employeeContactInformationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.contact_information_for_staff_on_leave.company_email
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	private String companyEmail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.contact_information_for_staff_on_leave.contact_information_for_staff_on_leave_id
	 * @return  the value of employee.contact_information_for_staff_on_leave.contact_information_for_staff_on_leave_id
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public Integer getContactInformationForStaffOnLeaveId() {
		return contactInformationForStaffOnLeaveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.contact_information_for_staff_on_leave.contact_information_for_staff_on_leave_id
	 * @param contactInformationForStaffOnLeaveId  the value for employee.contact_information_for_staff_on_leave.contact_information_for_staff_on_leave_id
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public void setContactInformationForStaffOnLeaveId(Integer contactInformationForStaffOnLeaveId) {
		this.contactInformationForStaffOnLeaveId = contactInformationForStaffOnLeaveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.contact_information_for_staff_on_leave.employee_contact_information_id
	 * @return  the value of employee.contact_information_for_staff_on_leave.employee_contact_information_id
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public Integer getEmployeeContactInformationId() {
		return employeeContactInformationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.contact_information_for_staff_on_leave.employee_contact_information_id
	 * @param employeeContactInformationId  the value for employee.contact_information_for_staff_on_leave.employee_contact_information_id
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public void setEmployeeContactInformationId(Integer employeeContactInformationId) {
		this.employeeContactInformationId = employeeContactInformationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.contact_information_for_staff_on_leave.company_email
	 * @return  the value of employee.contact_information_for_staff_on_leave.company_email
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public String getCompanyEmail() {
		return companyEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.contact_information_for_staff_on_leave.company_email
	 * @param companyEmail  the value for employee.contact_information_for_staff_on_leave.company_email
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public void setCompanyEmail(String companyEmail) {
		this.companyEmail = companyEmail == null ? null : companyEmail.trim();
	}
}