package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ContactInformationForStaffOnLeaveMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	long countByExample(ContactInformationForStaffOnLeaveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	int deleteByExample(ContactInformationForStaffOnLeaveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	int deleteByPrimaryKey(Integer contactInformationForStaffOnLeaveId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	int insert(ContactInformationForStaffOnLeave row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	int insertSelective(ContactInformationForStaffOnLeave row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	List<ContactInformationForStaffOnLeave> selectByExample(ContactInformationForStaffOnLeaveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	ContactInformationForStaffOnLeave selectByPrimaryKey(Integer contactInformationForStaffOnLeaveId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	int updateByExampleSelective(@Param("row") ContactInformationForStaffOnLeave row,
			@Param("example") ContactInformationForStaffOnLeaveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	int updateByExample(@Param("row") ContactInformationForStaffOnLeave row,
			@Param("example") ContactInformationForStaffOnLeaveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	int updateByPrimaryKeySelective(ContactInformationForStaffOnLeave row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.contact_information_for_staff_on_leave
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	int updateByPrimaryKey(ContactInformationForStaffOnLeave row);
}