package com.employee.managementapi.infrastructure.employee;

import java.util.ArrayList;
import java.util.List;

public class DatabaseSkillExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public DatabaseSkillExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDatabaseSkillIdIsNull() {
			addCriterion("database_skill_id is null");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdIsNotNull() {
			addCriterion("database_skill_id is not null");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdEqualTo(Integer value) {
			addCriterion("database_skill_id =", value, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdNotEqualTo(Integer value) {
			addCriterion("database_skill_id <>", value, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdGreaterThan(Integer value) {
			addCriterion("database_skill_id >", value, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("database_skill_id >=", value, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdLessThan(Integer value) {
			addCriterion("database_skill_id <", value, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdLessThanOrEqualTo(Integer value) {
			addCriterion("database_skill_id <=", value, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdIn(List<Integer> values) {
			addCriterion("database_skill_id in", values, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdNotIn(List<Integer> values) {
			addCriterion("database_skill_id not in", values, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdBetween(Integer value1, Integer value2) {
			addCriterion("database_skill_id between", value1, value2, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillIdNotBetween(Integer value1, Integer value2) {
			addCriterion("database_skill_id not between", value1, value2, "databaseSkillId");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameIsNull() {
			addCriterion("database_skill_name is null");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameIsNotNull() {
			addCriterion("database_skill_name is not null");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameEqualTo(String value) {
			addCriterion("database_skill_name =", value, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameNotEqualTo(String value) {
			addCriterion("database_skill_name <>", value, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameGreaterThan(String value) {
			addCriterion("database_skill_name >", value, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameGreaterThanOrEqualTo(String value) {
			addCriterion("database_skill_name >=", value, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameLessThan(String value) {
			addCriterion("database_skill_name <", value, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameLessThanOrEqualTo(String value) {
			addCriterion("database_skill_name <=", value, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameLike(String value) {
			addCriterion("database_skill_name like", value, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameNotLike(String value) {
			addCriterion("database_skill_name not like", value, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameIn(List<String> values) {
			addCriterion("database_skill_name in", values, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameNotIn(List<String> values) {
			addCriterion("database_skill_name not in", values, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameBetween(String value1, String value2) {
			addCriterion("database_skill_name between", value1, value2, "databaseSkillName");
			return (Criteria) this;
		}

		public Criteria andDatabaseSkillNameNotBetween(String value1, String value2) {
			addCriterion("database_skill_name not between", value1, value2, "databaseSkillName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.database_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee.database_skill
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 23 17:01:09 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}