package com.employee.managementapi.infrastructure.employee;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DivisionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(DivisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(DivisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer divisionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(Division row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(Division row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<Division> selectByExample(DivisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	Division selectByPrimaryKey(Integer divisionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") Division row, @Param("example") DivisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") Division row, @Param("example") DivisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(Division row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.division
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(Division row);
}