package com.employee.managementapi.infrastructure.employee;

import java.util.ArrayList;
import java.util.List;

public class EmployeeStatusExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public EmployeeStatusExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andEmployeeStatusIdIsNull() {
			addCriterion("employee_status_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdIsNotNull() {
			addCriterion("employee_status_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdEqualTo(Integer value) {
			addCriterion("employee_status_id =", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdNotEqualTo(Integer value) {
			addCriterion("employee_status_id <>", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdGreaterThan(Integer value) {
			addCriterion("employee_status_id >", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employee_status_id >=", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdLessThan(Integer value) {
			addCriterion("employee_status_id <", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdLessThanOrEqualTo(Integer value) {
			addCriterion("employee_status_id <=", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdIn(List<Integer> values) {
			addCriterion("employee_status_id in", values, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdNotIn(List<Integer> values) {
			addCriterion("employee_status_id not in", values, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdBetween(Integer value1, Integer value2) {
			addCriterion("employee_status_id between", value1, value2, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employee_status_id not between", value1, value2, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameIsNull() {
			addCriterion("employee_status_name is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameIsNotNull() {
			addCriterion("employee_status_name is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameEqualTo(String value) {
			addCriterion("employee_status_name =", value, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameNotEqualTo(String value) {
			addCriterion("employee_status_name <>", value, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameGreaterThan(String value) {
			addCriterion("employee_status_name >", value, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameGreaterThanOrEqualTo(String value) {
			addCriterion("employee_status_name >=", value, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameLessThan(String value) {
			addCriterion("employee_status_name <", value, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameLessThanOrEqualTo(String value) {
			addCriterion("employee_status_name <=", value, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameLike(String value) {
			addCriterion("employee_status_name like", value, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameNotLike(String value) {
			addCriterion("employee_status_name not like", value, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameIn(List<String> values) {
			addCriterion("employee_status_name in", values, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameNotIn(List<String> values) {
			addCriterion("employee_status_name not in", values, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameBetween(String value1, String value2) {
			addCriterion("employee_status_name between", value1, value2, "employeeStatusName");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusNameNotBetween(String value1, String value2) {
			addCriterion("employee_status_name not between", value1, value2, "employeeStatusName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.employee_status
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee.employee_status
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 23 17:01:09 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}