package com.employee.managementapi.infrastructure.employee;

import java.util.ArrayList;
import java.util.List;

public class EmployeeAddressExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public EmployeeAddressExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andEmployeeAddressIdIsNull() {
			addCriterion("employee_address_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdIsNotNull() {
			addCriterion("employee_address_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdEqualTo(Integer value) {
			addCriterion("employee_address_id =", value, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdNotEqualTo(Integer value) {
			addCriterion("employee_address_id <>", value, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdGreaterThan(Integer value) {
			addCriterion("employee_address_id >", value, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employee_address_id >=", value, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdLessThan(Integer value) {
			addCriterion("employee_address_id <", value, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdLessThanOrEqualTo(Integer value) {
			addCriterion("employee_address_id <=", value, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdIn(List<Integer> values) {
			addCriterion("employee_address_id in", values, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdNotIn(List<Integer> values) {
			addCriterion("employee_address_id not in", values, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdBetween(Integer value1, Integer value2) {
			addCriterion("employee_address_id between", value1, value2, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeAddressIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employee_address_id not between", value1, value2, "employeeAddressId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNull() {
			addCriterion("employee_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNotNull() {
			addCriterion("employee_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdEqualTo(Integer value) {
			addCriterion("employee_id =", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotEqualTo(Integer value) {
			addCriterion("employee_id <>", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThan(Integer value) {
			addCriterion("employee_id >", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employee_id >=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThan(Integer value) {
			addCriterion("employee_id <", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThanOrEqualTo(Integer value) {
			addCriterion("employee_id <=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIn(List<Integer> values) {
			addCriterion("employee_id in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotIn(List<Integer> values) {
			addCriterion("employee_id not in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdBetween(Integer value1, Integer value2) {
			addCriterion("employee_id between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employee_id not between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andPostCodeIsNull() {
			addCriterion("post_code is null");
			return (Criteria) this;
		}

		public Criteria andPostCodeIsNotNull() {
			addCriterion("post_code is not null");
			return (Criteria) this;
		}

		public Criteria andPostCodeEqualTo(String value) {
			addCriterion("post_code =", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotEqualTo(String value) {
			addCriterion("post_code <>", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeGreaterThan(String value) {
			addCriterion("post_code >", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeGreaterThanOrEqualTo(String value) {
			addCriterion("post_code >=", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeLessThan(String value) {
			addCriterion("post_code <", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeLessThanOrEqualTo(String value) {
			addCriterion("post_code <=", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeLike(String value) {
			addCriterion("post_code like", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotLike(String value) {
			addCriterion("post_code not like", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeIn(List<String> values) {
			addCriterion("post_code in", values, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotIn(List<String> values) {
			addCriterion("post_code not in", values, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeBetween(String value1, String value2) {
			addCriterion("post_code between", value1, value2, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotBetween(String value1, String value2) {
			addCriterion("post_code not between", value1, value2, "postCode");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.employee_address
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee.employee_address
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 23 17:01:09 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}