package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmployeeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer employeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(Employee row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(Employee row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<Employee> selectByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	Employee selectByPrimaryKey(Integer employeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") Employee row, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") Employee row, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(Employee row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(Employee row);

	/**
	 * シーケンス デフォルト設定
	 * 
	 * @return 新しく採番したシーケンス
	 */
	int selectNextval();

}