package com.employee.managementapi.infrastructure.employee;

import java.util.ArrayList;
import java.util.List;

public class EmployeeProgrammingSkillExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public EmployeeProgrammingSkillExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andEmployeeProgrammingSkillIdIsNull() {
			addCriterion("employee_programming_skill_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdIsNotNull() {
			addCriterion("employee_programming_skill_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdEqualTo(Integer value) {
			addCriterion("employee_programming_skill_id =", value, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdNotEqualTo(Integer value) {
			addCriterion("employee_programming_skill_id <>", value, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdGreaterThan(Integer value) {
			addCriterion("employee_programming_skill_id >", value, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employee_programming_skill_id >=", value, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdLessThan(Integer value) {
			addCriterion("employee_programming_skill_id <", value, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdLessThanOrEqualTo(Integer value) {
			addCriterion("employee_programming_skill_id <=", value, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdIn(List<Integer> values) {
			addCriterion("employee_programming_skill_id in", values, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdNotIn(List<Integer> values) {
			addCriterion("employee_programming_skill_id not in", values, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdBetween(Integer value1, Integer value2) {
			addCriterion("employee_programming_skill_id between", value1, value2, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andEmployeeProgrammingSkillIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employee_programming_skill_id not between", value1, value2, "employeeProgrammingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdIsNull() {
			addCriterion("programming_skill_id is null");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdIsNotNull() {
			addCriterion("programming_skill_id is not null");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdEqualTo(Integer value) {
			addCriterion("programming_skill_id =", value, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdNotEqualTo(Integer value) {
			addCriterion("programming_skill_id <>", value, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdGreaterThan(Integer value) {
			addCriterion("programming_skill_id >", value, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("programming_skill_id >=", value, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdLessThan(Integer value) {
			addCriterion("programming_skill_id <", value, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdLessThanOrEqualTo(Integer value) {
			addCriterion("programming_skill_id <=", value, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdIn(List<Integer> values) {
			addCriterion("programming_skill_id in", values, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdNotIn(List<Integer> values) {
			addCriterion("programming_skill_id not in", values, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdBetween(Integer value1, Integer value2) {
			addCriterion("programming_skill_id between", value1, value2, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andProgrammingSkillIdNotBetween(Integer value1, Integer value2) {
			addCriterion("programming_skill_id not between", value1, value2, "programmingSkillId");
			return (Criteria) this;
		}

		public Criteria andSkillLevelIsNull() {
			addCriterion("skill_level is null");
			return (Criteria) this;
		}

		public Criteria andSkillLevelIsNotNull() {
			addCriterion("skill_level is not null");
			return (Criteria) this;
		}

		public Criteria andSkillLevelEqualTo(Integer value) {
			addCriterion("skill_level =", value, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andSkillLevelNotEqualTo(Integer value) {
			addCriterion("skill_level <>", value, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andSkillLevelGreaterThan(Integer value) {
			addCriterion("skill_level >", value, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andSkillLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("skill_level >=", value, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andSkillLevelLessThan(Integer value) {
			addCriterion("skill_level <", value, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andSkillLevelLessThanOrEqualTo(Integer value) {
			addCriterion("skill_level <=", value, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andSkillLevelIn(List<Integer> values) {
			addCriterion("skill_level in", values, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andSkillLevelNotIn(List<Integer> values) {
			addCriterion("skill_level not in", values, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andSkillLevelBetween(Integer value1, Integer value2) {
			addCriterion("skill_level between", value1, value2, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andSkillLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("skill_level not between", value1, value2, "skillLevel");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNull() {
			addCriterion("employee_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNotNull() {
			addCriterion("employee_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdEqualTo(Integer value) {
			addCriterion("employee_id =", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotEqualTo(Integer value) {
			addCriterion("employee_id <>", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThan(Integer value) {
			addCriterion("employee_id >", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employee_id >=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThan(Integer value) {
			addCriterion("employee_id <", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThanOrEqualTo(Integer value) {
			addCriterion("employee_id <=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIn(List<Integer> values) {
			addCriterion("employee_id in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotIn(List<Integer> values) {
			addCriterion("employee_id not in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdBetween(Integer value1, Integer value2) {
			addCriterion("employee_id between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employee_id not between", value1, value2, "employeeId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.employee_programming_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee.employee_programming_skill
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 23 17:01:09 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}