package com.employee.managementapi.infrastructure.employee;

public class EmployeeInfrastructureSkill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_infrastructure_skill.employee_infrastructure_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeInfrastructureSkillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_infrastructure_skill.infrastructure_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer infrastructureSkillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_infrastructure_skill.skill_level
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer skillLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_infrastructure_skill.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_infrastructure_skill.employee_infrastructure_skill_id
	 * @return  the value of employee.employee_infrastructure_skill.employee_infrastructure_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeInfrastructureSkillId() {
		return employeeInfrastructureSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_infrastructure_skill.employee_infrastructure_skill_id
	 * @param employeeInfrastructureSkillId  the value for employee.employee_infrastructure_skill.employee_infrastructure_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeInfrastructureSkillId(Integer employeeInfrastructureSkillId) {
		this.employeeInfrastructureSkillId = employeeInfrastructureSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_infrastructure_skill.infrastructure_skill_id
	 * @return  the value of employee.employee_infrastructure_skill.infrastructure_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getInfrastructureSkillId() {
		return infrastructureSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_infrastructure_skill.infrastructure_skill_id
	 * @param infrastructureSkillId  the value for employee.employee_infrastructure_skill.infrastructure_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setInfrastructureSkillId(Integer infrastructureSkillId) {
		this.infrastructureSkillId = infrastructureSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_infrastructure_skill.skill_level
	 * @return  the value of employee.employee_infrastructure_skill.skill_level
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getSkillLevel() {
		return skillLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_infrastructure_skill.skill_level
	 * @param skillLevel  the value for employee.employee_infrastructure_skill.skill_level
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setSkillLevel(Integer skillLevel) {
		this.skillLevel = skillLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_infrastructure_skill.employee_id
	 * @return  the value of employee.employee_infrastructure_skill.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_infrastructure_skill.employee_id
	 * @param employeeId  the value for employee.employee_infrastructure_skill.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}
}