package com.employee.managementapi.infrastructure.employee;

public class EmployeeFrameworkSkill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_framework_skill.employee_framework_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeFrameworkSkillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_framework_skill.framework_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer frameworkSkillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_framework_skill.skill_level
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer skillLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_framework_skill.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_framework_skill.employee_framework_skill_id
	 * @return  the value of employee.employee_framework_skill.employee_framework_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeFrameworkSkillId() {
		return employeeFrameworkSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_framework_skill.employee_framework_skill_id
	 * @param employeeFrameworkSkillId  the value for employee.employee_framework_skill.employee_framework_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeFrameworkSkillId(Integer employeeFrameworkSkillId) {
		this.employeeFrameworkSkillId = employeeFrameworkSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_framework_skill.framework_skill_id
	 * @return  the value of employee.employee_framework_skill.framework_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getFrameworkSkillId() {
		return frameworkSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_framework_skill.framework_skill_id
	 * @param frameworkSkillId  the value for employee.employee_framework_skill.framework_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setFrameworkSkillId(Integer frameworkSkillId) {
		this.frameworkSkillId = frameworkSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_framework_skill.skill_level
	 * @return  the value of employee.employee_framework_skill.skill_level
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getSkillLevel() {
		return skillLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_framework_skill.skill_level
	 * @param skillLevel  the value for employee.employee_framework_skill.skill_level
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setSkillLevel(Integer skillLevel) {
		this.skillLevel = skillLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_framework_skill.employee_id
	 * @return  the value of employee.employee_framework_skill.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_framework_skill.employee_id
	 * @param employeeId  the value for employee.employee_framework_skill.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}
}