package com.employee.managementapi.infrastructure.employee;

public class EmployeeDatabaseSkill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_database_skill.employee_database_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeDatabaseSkillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_database_skill.database_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer databaseSkillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_database_skill.skill_level
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer skillLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_database_skill.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_database_skill.employee_database_skill_id
	 * @return  the value of employee.employee_database_skill.employee_database_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeDatabaseSkillId() {
		return employeeDatabaseSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_database_skill.employee_database_skill_id
	 * @param employeeDatabaseSkillId  the value for employee.employee_database_skill.employee_database_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeDatabaseSkillId(Integer employeeDatabaseSkillId) {
		this.employeeDatabaseSkillId = employeeDatabaseSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_database_skill.database_skill_id
	 * @return  the value of employee.employee_database_skill.database_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getDatabaseSkillId() {
		return databaseSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_database_skill.database_skill_id
	 * @param databaseSkillId  the value for employee.employee_database_skill.database_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDatabaseSkillId(Integer databaseSkillId) {
		this.databaseSkillId = databaseSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_database_skill.skill_level
	 * @return  the value of employee.employee_database_skill.skill_level
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getSkillLevel() {
		return skillLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_database_skill.skill_level
	 * @param skillLevel  the value for employee.employee_database_skill.skill_level
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setSkillLevel(Integer skillLevel) {
		this.skillLevel = skillLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_database_skill.employee_id
	 * @return  the value of employee.employee_database_skill.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_database_skill.employee_id
	 * @param employeeId  the value for employee.employee_database_skill.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}
}