package com.employee.managementapi.infrastructure.employee;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EmployeeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public EmployeeExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andEmployeeIdIsNull() {
			addCriterion("employee_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIsNotNull() {
			addCriterion("employee_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdEqualTo(Integer value) {
			addCriterion("employee_id =", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotEqualTo(Integer value) {
			addCriterion("employee_id <>", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThan(Integer value) {
			addCriterion("employee_id >", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employee_id >=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThan(Integer value) {
			addCriterion("employee_id <", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdLessThanOrEqualTo(Integer value) {
			addCriterion("employee_id <=", value, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdIn(List<Integer> values) {
			addCriterion("employee_id in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotIn(List<Integer> values) {
			addCriterion("employee_id not in", values, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdBetween(Integer value1, Integer value2) {
			addCriterion("employee_id between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andEmployeeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employee_id not between", value1, value2, "employeeId");
			return (Criteria) this;
		}

		public Criteria andGenderIdIsNull() {
			addCriterion("gender_id is null");
			return (Criteria) this;
		}

		public Criteria andGenderIdIsNotNull() {
			addCriterion("gender_id is not null");
			return (Criteria) this;
		}

		public Criteria andGenderIdEqualTo(Integer value) {
			addCriterion("gender_id =", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdNotEqualTo(Integer value) {
			addCriterion("gender_id <>", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdGreaterThan(Integer value) {
			addCriterion("gender_id >", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("gender_id >=", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdLessThan(Integer value) {
			addCriterion("gender_id <", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdLessThanOrEqualTo(Integer value) {
			addCriterion("gender_id <=", value, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdIn(List<Integer> values) {
			addCriterion("gender_id in", values, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdNotIn(List<Integer> values) {
			addCriterion("gender_id not in", values, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdBetween(Integer value1, Integer value2) {
			addCriterion("gender_id between", value1, value2, "genderId");
			return (Criteria) this;
		}

		public Criteria andGenderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("gender_id not between", value1, value2, "genderId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdIsNull() {
			addCriterion("employee_status_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdIsNotNull() {
			addCriterion("employee_status_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdEqualTo(Integer value) {
			addCriterion("employee_status_id =", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdNotEqualTo(Integer value) {
			addCriterion("employee_status_id <>", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdGreaterThan(Integer value) {
			addCriterion("employee_status_id >", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employee_status_id >=", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdLessThan(Integer value) {
			addCriterion("employee_status_id <", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdLessThanOrEqualTo(Integer value) {
			addCriterion("employee_status_id <=", value, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdIn(List<Integer> values) {
			addCriterion("employee_status_id in", values, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdNotIn(List<Integer> values) {
			addCriterion("employee_status_id not in", values, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdBetween(Integer value1, Integer value2) {
			addCriterion("employee_status_id between", value1, value2, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeStatusIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employee_status_id not between", value1, value2, "employeeStatusId");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeIsNull() {
			addCriterion("employee_code is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeIsNotNull() {
			addCriterion("employee_code is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeEqualTo(String value) {
			addCriterion("employee_code =", value, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeNotEqualTo(String value) {
			addCriterion("employee_code <>", value, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeGreaterThan(String value) {
			addCriterion("employee_code >", value, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeGreaterThanOrEqualTo(String value) {
			addCriterion("employee_code >=", value, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeLessThan(String value) {
			addCriterion("employee_code <", value, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeLessThanOrEqualTo(String value) {
			addCriterion("employee_code <=", value, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeLike(String value) {
			addCriterion("employee_code like", value, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeNotLike(String value) {
			addCriterion("employee_code not like", value, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeIn(List<String> values) {
			addCriterion("employee_code in", values, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeNotIn(List<String> values) {
			addCriterion("employee_code not in", values, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeBetween(String value1, String value2) {
			addCriterion("employee_code between", value1, value2, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andEmployeeCodeNotBetween(String value1, String value2) {
			addCriterion("employee_code not between", value1, value2, "employeeCode");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIsNull() {
			addCriterion("family_name is null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIsNotNull() {
			addCriterion("family_name is not null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameEqualTo(String value) {
			addCriterion("family_name =", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotEqualTo(String value) {
			addCriterion("family_name <>", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameGreaterThan(String value) {
			addCriterion("family_name >", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameGreaterThanOrEqualTo(String value) {
			addCriterion("family_name >=", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLessThan(String value) {
			addCriterion("family_name <", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLessThanOrEqualTo(String value) {
			addCriterion("family_name <=", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameLike(String value) {
			addCriterion("family_name like", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotLike(String value) {
			addCriterion("family_name not like", value, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameIn(List<String> values) {
			addCriterion("family_name in", values, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotIn(List<String> values) {
			addCriterion("family_name not in", values, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameBetween(String value1, String value2) {
			addCriterion("family_name between", value1, value2, "familyName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameNotBetween(String value1, String value2) {
			addCriterion("family_name not between", value1, value2, "familyName");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNull() {
			addCriterion("last_name is null");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNotNull() {
			addCriterion("last_name is not null");
			return (Criteria) this;
		}

		public Criteria andLastNameEqualTo(String value) {
			addCriterion("last_name =", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotEqualTo(String value) {
			addCriterion("last_name <>", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThan(String value) {
			addCriterion("last_name >", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThanOrEqualTo(String value) {
			addCriterion("last_name >=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThan(String value) {
			addCriterion("last_name <", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThanOrEqualTo(String value) {
			addCriterion("last_name <=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLike(String value) {
			addCriterion("last_name like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotLike(String value) {
			addCriterion("last_name not like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameIn(List<String> values) {
			addCriterion("last_name in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotIn(List<String> values) {
			addCriterion("last_name not in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameBetween(String value1, String value2) {
			addCriterion("last_name between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotBetween(String value1, String value2) {
			addCriterion("last_name not between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaIsNull() {
			addCriterion("family_name_furigana is null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaIsNotNull() {
			addCriterion("family_name_furigana is not null");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaEqualTo(String value) {
			addCriterion("family_name_furigana =", value, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaNotEqualTo(String value) {
			addCriterion("family_name_furigana <>", value, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaGreaterThan(String value) {
			addCriterion("family_name_furigana >", value, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaGreaterThanOrEqualTo(String value) {
			addCriterion("family_name_furigana >=", value, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaLessThan(String value) {
			addCriterion("family_name_furigana <", value, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaLessThanOrEqualTo(String value) {
			addCriterion("family_name_furigana <=", value, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaLike(String value) {
			addCriterion("family_name_furigana like", value, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaNotLike(String value) {
			addCriterion("family_name_furigana not like", value, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaIn(List<String> values) {
			addCriterion("family_name_furigana in", values, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaNotIn(List<String> values) {
			addCriterion("family_name_furigana not in", values, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaBetween(String value1, String value2) {
			addCriterion("family_name_furigana between", value1, value2, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andFamilyNameFuriganaNotBetween(String value1, String value2) {
			addCriterion("family_name_furigana not between", value1, value2, "familyNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaIsNull() {
			addCriterion("last_name_furigana is null");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaIsNotNull() {
			addCriterion("last_name_furigana is not null");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaEqualTo(String value) {
			addCriterion("last_name_furigana =", value, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaNotEqualTo(String value) {
			addCriterion("last_name_furigana <>", value, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaGreaterThan(String value) {
			addCriterion("last_name_furigana >", value, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaGreaterThanOrEqualTo(String value) {
			addCriterion("last_name_furigana >=", value, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaLessThan(String value) {
			addCriterion("last_name_furigana <", value, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaLessThanOrEqualTo(String value) {
			addCriterion("last_name_furigana <=", value, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaLike(String value) {
			addCriterion("last_name_furigana like", value, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaNotLike(String value) {
			addCriterion("last_name_furigana not like", value, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaIn(List<String> values) {
			addCriterion("last_name_furigana in", values, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaNotIn(List<String> values) {
			addCriterion("last_name_furigana not in", values, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaBetween(String value1, String value2) {
			addCriterion("last_name_furigana between", value1, value2, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andLastNameFuriganaNotBetween(String value1, String value2) {
			addCriterion("last_name_furigana not between", value1, value2, "lastNameFurigana");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthIsNull() {
			addCriterion("date_of_birth is null");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthIsNotNull() {
			addCriterion("date_of_birth is not null");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthEqualTo(Date value) {
			addCriterionForJDBCDate("date_of_birth =", value, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthNotEqualTo(Date value) {
			addCriterionForJDBCDate("date_of_birth <>", value, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthGreaterThan(Date value) {
			addCriterionForJDBCDate("date_of_birth >", value, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("date_of_birth >=", value, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthLessThan(Date value) {
			addCriterionForJDBCDate("date_of_birth <", value, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("date_of_birth <=", value, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthIn(List<Date> values) {
			addCriterionForJDBCDate("date_of_birth in", values, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthNotIn(List<Date> values) {
			addCriterionForJDBCDate("date_of_birth not in", values, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("date_of_birth between", value1, value2, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andDateOfBirthNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("date_of_birth not between", value1, value2, "dateOfBirth");
			return (Criteria) this;
		}

		public Criteria andGradeIsNull() {
			addCriterion("grade is null");
			return (Criteria) this;
		}

		public Criteria andGradeIsNotNull() {
			addCriterion("grade is not null");
			return (Criteria) this;
		}

		public Criteria andGradeEqualTo(Integer value) {
			addCriterion("grade =", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeNotEqualTo(Integer value) {
			addCriterion("grade <>", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeGreaterThan(Integer value) {
			addCriterion("grade >", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
			addCriterion("grade >=", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeLessThan(Integer value) {
			addCriterion("grade <", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeLessThanOrEqualTo(Integer value) {
			addCriterion("grade <=", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeIn(List<Integer> values) {
			addCriterion("grade in", values, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeNotIn(List<Integer> values) {
			addCriterion("grade not in", values, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeBetween(Integer value1, Integer value2) {
			addCriterion("grade between", value1, value2, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeNotBetween(Integer value1, Integer value2) {
			addCriterion("grade not between", value1, value2, "grade");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("comment is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("comment is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("comment =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("comment <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("comment >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("comment >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("comment <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("comment <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("comment like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("comment not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("comment in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("comment not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("comment between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("comment not between", value1, value2, "comment");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.employee
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee.employee
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 23 17:01:09 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}