package com.employee.managementapi.infrastructure.employee;

import java.util.ArrayList;
import java.util.List;

public class FrameworkSkillExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public FrameworkSkillExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFrameworkSkillIdIsNull() {
			addCriterion("framework_skill_id is null");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdIsNotNull() {
			addCriterion("framework_skill_id is not null");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdEqualTo(Integer value) {
			addCriterion("framework_skill_id =", value, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdNotEqualTo(Integer value) {
			addCriterion("framework_skill_id <>", value, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdGreaterThan(Integer value) {
			addCriterion("framework_skill_id >", value, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("framework_skill_id >=", value, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdLessThan(Integer value) {
			addCriterion("framework_skill_id <", value, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdLessThanOrEqualTo(Integer value) {
			addCriterion("framework_skill_id <=", value, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdIn(List<Integer> values) {
			addCriterion("framework_skill_id in", values, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdNotIn(List<Integer> values) {
			addCriterion("framework_skill_id not in", values, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdBetween(Integer value1, Integer value2) {
			addCriterion("framework_skill_id between", value1, value2, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillIdNotBetween(Integer value1, Integer value2) {
			addCriterion("framework_skill_id not between", value1, value2, "frameworkSkillId");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameIsNull() {
			addCriterion("framework_skill_name is null");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameIsNotNull() {
			addCriterion("framework_skill_name is not null");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameEqualTo(String value) {
			addCriterion("framework_skill_name =", value, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameNotEqualTo(String value) {
			addCriterion("framework_skill_name <>", value, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameGreaterThan(String value) {
			addCriterion("framework_skill_name >", value, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameGreaterThanOrEqualTo(String value) {
			addCriterion("framework_skill_name >=", value, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameLessThan(String value) {
			addCriterion("framework_skill_name <", value, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameLessThanOrEqualTo(String value) {
			addCriterion("framework_skill_name <=", value, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameLike(String value) {
			addCriterion("framework_skill_name like", value, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameNotLike(String value) {
			addCriterion("framework_skill_name not like", value, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameIn(List<String> values) {
			addCriterion("framework_skill_name in", values, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameNotIn(List<String> values) {
			addCriterion("framework_skill_name not in", values, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameBetween(String value1, String value2) {
			addCriterion("framework_skill_name between", value1, value2, "frameworkSkillName");
			return (Criteria) this;
		}

		public Criteria andFrameworkSkillNameNotBetween(String value1, String value2) {
			addCriterion("framework_skill_name not between", value1, value2, "frameworkSkillName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.framework_skill
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee.framework_skill
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 23 17:01:09 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}