package com.employee.managementapi.infrastructure.employee;

public class InfrastructureSkill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.infrastructure_skill.infrastructure_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer infrastructureSkillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.infrastructure_skill.infrastructure_skill_name
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private String infrastructureSkillName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.infrastructure_skill.infrastructure_skill_id
	 * @return  the value of employee.infrastructure_skill.infrastructure_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getInfrastructureSkillId() {
		return infrastructureSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.infrastructure_skill.infrastructure_skill_id
	 * @param infrastructureSkillId  the value for employee.infrastructure_skill.infrastructure_skill_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setInfrastructureSkillId(Integer infrastructureSkillId) {
		this.infrastructureSkillId = infrastructureSkillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.infrastructure_skill.infrastructure_skill_name
	 * @return  the value of employee.infrastructure_skill.infrastructure_skill_name
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getInfrastructureSkillName() {
		return infrastructureSkillName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.infrastructure_skill.infrastructure_skill_name
	 * @param infrastructureSkillName  the value for employee.infrastructure_skill.infrastructure_skill_name
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setInfrastructureSkillName(String infrastructureSkillName) {
		this.infrastructureSkillName = infrastructureSkillName == null ? null : infrastructureSkillName.trim();
	}
}