package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface JoiningTheCompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(JoiningTheCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(JoiningTheCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer joiningTheCompanyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(JoiningTheCompany row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(JoiningTheCompany row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<JoiningTheCompany> selectByExample(JoiningTheCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	JoiningTheCompany selectByPrimaryKey(Integer joiningTheCompanyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") JoiningTheCompany row,
			@Param("example") JoiningTheCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") JoiningTheCompany row, @Param("example") JoiningTheCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(JoiningTheCompany row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.joining_the_company
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(JoiningTheCompany row);

	int selectNextval();
}