package com.employee.managementapi.infrastructure.employee;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;

@Builder
@AllArgsConstructor
public class JoiningTheCompany {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.joining_the_company.joining_the_company_id
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer joiningTheCompanyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.joining_the_company.employee_id
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employee.joining_the_company.joining_the_company_date
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	private Date joiningTheCompanyDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.joining_the_company.joining_the_company_id
	 * 
	 * @return the value of employee.joining_the_company.joining_the_company_id
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getJoiningTheCompanyId() {
		return joiningTheCompanyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.joining_the_company.joining_the_company_id
	 * 
	 * @param joiningTheCompanyId the value for
	 *                            employee.joining_the_company.joining_the_company_id
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public void setJoiningTheCompanyId(Integer joiningTheCompanyId) {
		this.joiningTheCompanyId = joiningTheCompanyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.joining_the_company.employee_id
	 * 
	 * @return the value of employee.joining_the_company.employee_id
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.joining_the_company.employee_id
	 * 
	 * @param employeeId the value for employee.joining_the_company.employee_id
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employee.joining_the_company.joining_the_company_date
	 * 
	 * @return the value of employee.joining_the_company.joining_the_company_date
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public Date getJoiningTheCompanyDate() {
		return joiningTheCompanyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employee.joining_the_company.joining_the_company_date
	 * 
	 * @param joiningTheCompanyDate the value for
	 *                              employee.joining_the_company.joining_the_company_date
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	public void setJoiningTheCompanyDate(Date joiningTheCompanyDate) {
		this.joiningTheCompanyDate = joiningTheCompanyDate;
	}

	/**
	 * ドメインオブジェクトからインスタンスを生成
	 * 
	 * @param domainJoiningCompany ドメインオブジェクト
	 * @return JoiningTheCompany
	 */
	public static JoiningTheCompany build(
			final com.employee.managementapi.employee.cycle.joining.JoiningTheCompany domainJoiningCompany) {
		return JoiningTheCompany.builder()
				.employeeId(domainJoiningCompany.getEmployeeId())
				.joiningTheCompanyDate(domainJoiningCompany.getJoiningTheCompanyDate())
				.build();
	}

	/**
	 * DBエンティティをドメインオブジェクトへ変換
	 * 
	 * @return ドメインオブジェクト
	 */
	public com.employee.managementapi.employee.cycle.joining.JoiningTheCompany toDomainJoiningCompany() {
		return com.employee.managementapi.employee.cycle.joining.JoiningTheCompany.builder()
				.employeeId(this.employeeId)
				.joiningTheCompanyDate(this.joiningTheCompanyDate)
				.build();
	}
}