package com.employee.managementapi.infrastructure.employee;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PositionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(PositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(PositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer positionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(Position row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(Position row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<Position> selectByExample(PositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	Position selectByPrimaryKey(Integer positionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") Position row, @Param("example") PositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") Position row, @Param("example") PositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(Position row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.position
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(Position row);
}