package com.employee.managementapi.infrastructure.employee;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(Project row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(Project row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<Project> selectByExample(ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	Project selectByPrimaryKey(Integer projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") Project row, @Param("example") ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") Project row, @Param("example") ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(Project row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.project
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(Project row);
}