package com.employee.managementapi.infrastructure.employee;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReinstatementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(ReinstatementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(ReinstatementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer reinstatementId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(Reinstatement row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(Reinstatement row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<Reinstatement> selectByExample(ReinstatementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	Reinstatement selectByPrimaryKey(Integer reinstatementId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") Reinstatement row, @Param("example") ReinstatementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") Reinstatement row, @Param("example") ReinstatementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(Reinstatement row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.reinstatement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(Reinstatement row);
}