package com.employee.managementapi.infrastructure.employee;

public class RetiredEmployee {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.retired_employee.retired_employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer retiredEmployeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.retired_employee.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Integer employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.retired_employee.returning_permission
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	private Boolean returningPermission;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.retired_employee.retired_employee_id
	 * @return  the value of employee.retired_employee.retired_employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getRetiredEmployeeId() {
		return retiredEmployeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.retired_employee.retired_employee_id
	 * @param retiredEmployeeId  the value for employee.retired_employee.retired_employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setRetiredEmployeeId(Integer retiredEmployeeId) {
		this.retiredEmployeeId = retiredEmployeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.retired_employee.employee_id
	 * @return  the value of employee.retired_employee.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.retired_employee.employee_id
	 * @param employeeId  the value for employee.retired_employee.employee_id
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.retired_employee.returning_permission
	 * @return  the value of employee.retired_employee.returning_permission
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Boolean getReturningPermission() {
		return returningPermission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.retired_employee.returning_permission
	 * @param returningPermission  the value for employee.retired_employee.returning_permission
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setReturningPermission(Boolean returningPermission) {
		this.returningPermission = returningPermission;
	}
}