package com.employee.managementapi.infrastructure.employee;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RetiredEmployeeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(RetiredEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(RetiredEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer retiredEmployeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(RetiredEmployee row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(RetiredEmployee row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<RetiredEmployee> selectByExample(RetiredEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	RetiredEmployee selectByPrimaryKey(Integer retiredEmployeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") RetiredEmployee row, @Param("example") RetiredEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") RetiredEmployee row, @Param("example") RetiredEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(RetiredEmployee row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(RetiredEmployee row);
}