package com.employee.managementapi.infrastructure.employee;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RetirementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(RetirementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(RetirementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer retirementId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(Retirement row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(Retirement row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<Retirement> selectByExample(RetirementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	Retirement selectByPrimaryKey(Integer retirementId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") Retirement row, @Param("example") RetirementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") Retirement row, @Param("example") RetirementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(Retirement row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retirement
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(Retirement row);
}