package com.employee.managementapi.infrastructure.employee;

import java.util.ArrayList;
import java.util.List;

public class RetiredEmployeeContactInformationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public RetiredEmployeeContactInformationExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRetiredEmployeeContactInformationIdIsNull() {
			addCriterion("retired_employee_contact_information_id is null");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdIsNotNull() {
			addCriterion("retired_employee_contact_information_id is not null");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdEqualTo(Integer value) {
			addCriterion("retired_employee_contact_information_id =", value, "retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdNotEqualTo(Integer value) {
			addCriterion("retired_employee_contact_information_id <>", value, "retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdGreaterThan(Integer value) {
			addCriterion("retired_employee_contact_information_id >", value, "retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("retired_employee_contact_information_id >=", value, "retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdLessThan(Integer value) {
			addCriterion("retired_employee_contact_information_id <", value, "retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdLessThanOrEqualTo(Integer value) {
			addCriterion("retired_employee_contact_information_id <=", value, "retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdIn(List<Integer> values) {
			addCriterion("retired_employee_contact_information_id in", values, "retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdNotIn(List<Integer> values) {
			addCriterion("retired_employee_contact_information_id not in", values,
					"retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdBetween(Integer value1, Integer value2) {
			addCriterion("retired_employee_contact_information_id between", value1, value2,
					"retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andRetiredEmployeeContactInformationIdNotBetween(Integer value1, Integer value2) {
			addCriterion("retired_employee_contact_information_id not between", value1, value2,
					"retiredEmployeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdIsNull() {
			addCriterion("employee_contact_information_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdIsNotNull() {
			addCriterion("employee_contact_information_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdEqualTo(Integer value) {
			addCriterion("employee_contact_information_id =", value, "employeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdNotEqualTo(Integer value) {
			addCriterion("employee_contact_information_id <>", value, "employeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdGreaterThan(Integer value) {
			addCriterion("employee_contact_information_id >", value, "employeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employee_contact_information_id >=", value, "employeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdLessThan(Integer value) {
			addCriterion("employee_contact_information_id <", value, "employeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdLessThanOrEqualTo(Integer value) {
			addCriterion("employee_contact_information_id <=", value, "employeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdIn(List<Integer> values) {
			addCriterion("employee_contact_information_id in", values, "employeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdNotIn(List<Integer> values) {
			addCriterion("employee_contact_information_id not in", values, "employeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdBetween(Integer value1, Integer value2) {
			addCriterion("employee_contact_information_id between", value1, value2, "employeeContactInformationId");
			return (Criteria) this;
		}

		public Criteria andEmployeeContactInformationIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employee_contact_information_id not between", value1, value2, "employeeContactInformationId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee.retired_employee_contact_information
	 * @mbg.generated  Mon Dec 26 23:16:33 JST 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee.retired_employee_contact_information
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 23 17:01:09 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}