package com.employee.managementapi.infrastructure.employee;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RetiredEmployeeContactInformationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	long countByExample(RetiredEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByExample(RetiredEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int deleteByPrimaryKey(Integer retiredEmployeeContactInformationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insert(RetiredEmployeeContactInformation row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int insertSelective(RetiredEmployeeContactInformation row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	List<RetiredEmployeeContactInformation> selectByExample(RetiredEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	RetiredEmployeeContactInformation selectByPrimaryKey(Integer retiredEmployeeContactInformationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExampleSelective(@Param("row") RetiredEmployeeContactInformation row,
			@Param("example") RetiredEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByExample(@Param("row") RetiredEmployeeContactInformation row,
			@Param("example") RetiredEmployeeContactInformationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKeySelective(RetiredEmployeeContactInformation row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table employee.retired_employee_contact_information
	 * 
	 * @mbg.generated Mon Dec 26 23:16:33 JST 2022
	 */
	int updateByPrimaryKey(RetiredEmployeeContactInformation row);
}