package com.employee.managementapi.infrastructure.employee;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.role.role_id
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.role.role_name
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	private String roleName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.role.role_id
	 * @return  the value of employee.role.role_id
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.role.role_id
	 * @param roleId  the value for employee.role.role_id
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.role.role_name
	 * @return  the value of employee.role.role_name
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.role.role_name
	 * @param roleName  the value for employee.role.role_name
	 * @mbg.generated  Wed Mar 01 20:18:56 JST 2023
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}
}