spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee_management?currentSchema=employee
    username: postgres
    password: postgres
  config:
    activate:
      on-profile: dev
  sql:
    init:
      schema-locations:
      - classpath:schema.sql
      data-locations:
      - classpath:data.sql
      mode: always
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 6048000